gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to Team Magma!\p"
	.string "We of Team Magma exist\n"
	.string "for the good of all people!\p"
	.string "As I'm sure you know, I'm the\n"
	.string "leader of Team Magma, MAXIE.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "We use these POKéMON to help us\n"
	.string "in our quest to reverse the changes\p"
	.string "to HOENN's climate.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who will be\n"
	.string "joining Team Magma.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "You'll be stationed in LITTLEROOT\n"
	.string "TOWN with one of our veterans.\p"
	.string "Take courage, and leap into the\n"
	.string "world of Team Magma where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "I hope to see you again later.\n"
	.string "Good luck, newest Magma Grunt.\p"
	.string "$"
