MagmaHideout_2F_2R_MapScripts::
	.byte 0

MagmaHideout_2F_2R_EventScript_Grunt15::
	msgbox MagmaHideout_2F_2R_Text_Grunt15PostBattle, MSGBOX_DEFAULT
	end

MagmaHideout_2F_2R_EventScript_Grunt6::
	msgbox MagmaHideout_2F_2R_Text_Grunt6PostBattle, MSGBOX_DEFAULT
	end

MagmaHideout_2F_2R_EventScript_Grunt7::
	msgbox MagmaHideout_2F_2R_Text_Grunt7PostBattle, MSGBOX_DEFAULT
	end

MagmaHideout_2F_2R_EventScript_Grunt8::
	msgbox MagmaHideout_2F_2R_Text_Grunt8PostBattle, MSGBOX_DEFAULT
	end

MagmaHideout_2F_2R_Text_Grunt15Intro:
	.string "I don't have a bone to pick with you.\n"
	.string "I'm just following orders!$"

MagmaHideout_2F_2R_Text_Grunt15Defeat:
	.string "I may have lost, but…$"

MagmaHideout_2F_2R_Text_Grunt15PostBattle:
	.string "We dug up something beyond belief!\n"
	.string "And, we got the BLUE ORB!\p"
	.string "All that's left is for our leader to…\n"
	.string "Fufufu… Fwahahaha!$"

MagmaHideout_2F_2R_Text_Grunt6Intro:
	.string "I can't stand heat. Maybe I should've\n"
	.string "joined TEAM AQUA instead…$"

MagmaHideout_2F_2R_Text_Grunt6Defeat:
	.string "Yeah, I really may not be right for\n"
	.string "TEAM MAGMA…$"

MagmaHideout_2F_2R_Text_Grunt6PostBattle:
	.string "I can't stand heat. Maybe I should've\n"
	.string "joined TEAM AQUA instead…$"

MagmaHideout_2F_2R_Text_Grunt7Intro:
	.string "You can hear tremors here sometimes.\p"
	.string "Could it be the volcano rattling?\n"
	.string "Or is it GROU…\p"
	.string "Whoops!\n"
	.string "No, no, never mind!$"

MagmaHideout_2F_2R_Text_Grunt7Defeat:
	.string "You're a fiery battler.\n"
	.string "Just like a volcano!$"

MagmaHideout_2F_2R_Text_Grunt7PostBattle:
	.string "You can hear tremors here sometimes.\p"
	.string "Could it be the volcano rattling?\n"
	.string "Or is it GROUDON?$"

MagmaHideout_2F_2R_Text_Grunt8Intro:
	.string "One of our guys was freaking out that\n"
	.string "he lost his MAGMA EMBLEM…\p"
	.string "Wait a minute!\n"
	.string "Was it you who found it?$"

MagmaHideout_2F_2R_Text_Grunt8Defeat:
	.string "I'm having trouble believing this…$"

MagmaHideout_2F_2R_Text_Grunt8PostBattle:
	.string "One of our guys was freaking out that\n"
	.string "he lost his MAGMA EMBLEM…$"

